# Generated by Django 4.0.4 on 2022-06-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='new/images/')),
                ('url', models.URLField(blank=True)),
                ('date_new', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
    ]
